version: '3.8'

networks:
  joonik_app_network:
    driver: bridge

services:
  database:
    image: mysql:8.0
    container_name: mysql_database
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    networks:
      - joonik_app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    volumes:
      - ./backend:/var/www/html
      - ./backend/.env:/var/www/html/.env
    ports:
      - "9000:9000"
    environment:
      - API_KEY_AUTH="location_PmTRCYoGWVZhkHaOqxzV"
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - database
    networks:
      - joonik_app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:9000
      - REACT_APP_API_KEY="location_PmTRCYoGWVZhkHaOqxzV"
    depends_on:
      - backend
    networks:
      - joonik_app_network
